### PR TITLE
fix bug

### LINKED ISSUE #268: Robot name headline bug
The Robot name in the headline does not change when modifiyng the robot name. It only changes after refreshing

### PR DESCRIPTION
**Pull request by SamuABC**
resolves #268 

The robot name in the headline now also changes when modifying the robot name in the table

### CODE REVIEW

File: frontend/app/pages/details/DatasetTable.tsx [hunk 1]
```diff
@@ -248,6 +251,7 @@ export function ShowDatasets({
                     e.stopPropagation()
                     setRobotMenuOpened(-1)
                     data.robots[index] = fieldValue
+                    await onRobotsUpdate(data.robots)
```
Comment (DerSimi) [inline frontend/app/pages/details/DatasetTable.tsx:254]:
```suggestion
                    onRobotsUpdate(data.robots)
```

File: frontend/app/pages/details/DatasetTable.tsx [hunk 2]
```diff
@@ -236,6 +238,7 @@ export function ShowDatasets({
                     event.preventDefault(); // Prevent newline
                     setRobotMenuOpened(-1);
                     data.robots[index] = fieldValue
+                    await onRobotsUpdate(data.robots)
```
Comment (DerSimi) [inline frontend/app/pages/details/DatasetTable.tsx:241]:
```suggestion
                    onRobotsUpdate(data.robots)
```

**Review by DerSimi — COMMENTED** [review]
Hi @SamuABC, it works now correctly. But please, look at my suggestions, the await key word is not needed here.

**Review by DerSimi — APPROVED** [review]
